plugins {
    id 'java'
}

group = 'org.user'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {

    // PicoContainer for dependency injection
    implementation 'org.picocontainer:picocontainer:2.15'

    implementation 'org.eclipse.jetty:jetty-server:11.0.18'
    implementation 'org.eclipse.jetty:jetty-servlet:11.0.18'
    implementation 'com.h2database:h2:2.2.224'
    implementation 'com.fasterxml.jackson.core:jackson-core:2.15.2'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.15.2'
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.15.2'
    implementation 'jakarta.servlet:jakarta.servlet-api:5.0.0'
    implementation 'org.slf4j:slf4j-simple:2.0.9'

    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.0'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

}

test {
    useJUnitPlatform()
}